### ISSUE TITLE
Sync error index update when recipients "0"

### ISSUE THREAD

**Issue by smai2018** [SigwoTechnologies/explorer#3]
node scripts/sync.js index update

script launched with pid: 1507
/root/explorer/lib/explorer.js:503
          module.exports.syncLoop(tx.vout.length, function (loop) {

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/explorer.js:503:42
    at Request._callback (/root/explorer/lib/explorer.js:222:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

![image](https://user-images.githubusercontent.com/37613028/42728956-9a8891ca-87c8-11e8-8fbb-2b3ccb172e2f.png)

**Comment by project-qmc** [comment]
lib/explorer.js : 


      module.exports.get_rawtransaction(input.txid, function(tx){
        if (tx) {
      if (tx.vout) {
        console.log('tx.vout: %o', tx.vout);
          module.exports.syncLoop(tx.vout.length, function (loop) {
            var i = loop.iteration();
            if (tx.vout[i].n == input.vout) {
              //module.exports.convert_to_satoshi(parseFloat(tx.vout[i].value), function(amount_sat){
              if (tx.vout[i].scriptPubKey.addresses) {
                addresses.push({hash: tx.vout[i].scriptPubKey.addresses[0], amount:tx.vout[i].value});  
              }
                loop.break(true);
                loop.next();
              //});
            } else {
              loop.next();
            } 
          }, function(){
            return cb(addresses);
          });
        } else {
          return cb();
        }
    } else {//Added
      return cb(); 
    } 
      });
    }
  },
